# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       libsp-measure
Summary:    API for measuring system/process resource usage
Version:    1.3.5
Release:    1
Group:      Development/Libraries
License:    LGPLv2+
URL:        http://www.gitorious.org/+maemo-tools-developers/maemo-tools/sp-measure
Source0:    %{name}-%{version}.tar.gz
Source100:  libsp-measure.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  automake
BuildRequires:  doxygen
BuildRequires:  libtool


%description
API for taking system/process resource usage snaphots and calculating difference between two snapshots of the same type.


%package devel
Summary:    Development files for libsmeasure library
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   libsp-measure >= %{version}

%description devel
libspmeasure headeres and static libraries.


%prep
%setup -q -n src

# >> setup
# << setup

%build
# >> build pre
autoreconf -fvi
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
rm -rf %{buildroot}/usr/lib/*a

# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig





%files
%defattr(-,root,root,-)
# >> files
%{_libdir}/libspmeasure.so.*
%doc COPYING README
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%{_libdir}/libspmeasure.so
%{_includedir}/*.h
/usr/share/doc/sp-measure/libsp-measure-dev/res-monitor.c
%{_mandir}/man3/*
# << files devel

